language: java
jdk: oraclejdk8

branches:
  only:
    - master
script:
  - bash gradlew decryptFiles
  - rm application-*.yml.encrypted
  - bash gradlew encryptFiles

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
